package com.advent.oc.domain.security;
public enum CFIEquitiesGroup
{
	COMMON_STOCK, PREFERRED_STOCK, CONVERTIBLE_STOCK, PREFRRED_CONVERTIBLE_STOCK, HEDGE_FUND, ETF, MUTUAL_FUND, OTHER_FUND, OTHER_EQUITY, DEPOSITORY_RECEIPT, REIT;
}
