package com.advent.oc.domain.security;
public enum CFIInstrumentCategory
{
	E_EQUITIES, D_DEBT, R_RIGHTS, O_OPTIONS, F_FUTURES, M_OTHERS, C_COLLECTIVE_INVESTMENT_VEHICLES, S_SWAPS, H_NONLISTED_OPTIONS, I_SPOT, J_FORWARD, K_STRATEGIES, L_FINANCING, T_REFERENTIAL_INSTRUMENTS;
}
