package com.advent.oc.domain.security;
public enum SecuritySubGroup
{
	ADR, GDR, TBILL, TNOTE, TIPS, STRIPS, CORPORATE_BONDS, CONVERTIBLE_BONDS, BONDS_W_WARRANTS, CMO, MORTGAGE_PASSTHROUGH, CALLABLE_PASSTHROUGH;
}
